<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>EDU4ALL</title>
  <link rel="stylesheet" href="styles/swiper-bundle.min.css">
  <link rel="stylesheet" href="styles/carrucel.css">
  <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
  <link rel="icon" href="SRC/logo_god.png">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>

  <?php
  include 'navbar.php'
  ?>

  <section class="home">
    <div class="media-icons">

      <a href="https://www.instagram.com/edu4all_oficial/"><i class="uil uil-instagram"></i></a>
      <a href="https://x.com/CaleidosOficial"><i class="uil uil-twitter"></i></a>
    </div>

    <div class="swiper bg-slider">
      <div class="swiper-wrapper">
        <div class="swiper-slide">
          <img src="SRC/Carrucel/1.png" alt="">
          <div class="text-content">
            <h2 class="title">Edu4All</h2>
            <p>Edu4All is a project generated by students
            of the University of Colima with the purpose of giving an equal education to children</p>
          </div>
        </div>
        <div class="swiper-slide dark-layer">
          <img src="SRC/Carrucel/EDU4ALL1.png" alt="">
          <div class="text-content">
            <h2 class="title">Edu4All</h2>
            <p>Edu4All is an educational platform created to ensure that all children have access
            to quality content. With a wide variety of resources, the page seeks to promote learning
            equitable and offer opportunities that help the comprehensive development of each student..</p>
            
          </div>
        </div>
        <div class="swiper-slide dark-layer">
          <img src="SRC/Carrucel/3.png" alt="">
          <div class="text-content">
            <h2 class="title">Edu4All</h2>
            <p>Edu4All is dedicated to creating a space where all children can learn 
              on equal terms. Through its accessible resources, the page promotes
              an inclusive education that supports the academic and personal growth of each student..</p>
            
          </div>
        </div>
        <div class="swiper-slide">
          <img src="SRC/Carrucel/4.png" alt="">
          <div class="text-content">
            <h2 class="title">Edu4All</h2>
            <p>Edu4All is committed to offering every child the opportunity to access
              to quality education. Through its platform, the page provides
              educational resources that encourage learning and help children achieve
              your academic goals..</p>
            
          </div>
        </div>
      </div>
    </div>
    
    <div class="bg-slider-thumbs">
      <div class="swiper-wrapper thumbs-container">
        <img src="SRC/Carrucel/1.png" class="swiper-slide" alt="">
        <img src="SRC/Carrucel/EDU4ALL1.png" class="swiper-slide" alt="">
        <img src="SRC/Carrucel/3.png" class="swiper-slide" alt="">
        <img src="SRC/Carrucel/4.png" class="swiper-slide" alt="">
      </div>
    </div>
  </section>

  <script src="swiper-bundle.min.js"></script>
  <script src="main.js"></script>

</body>
</html>

<script type="text/javascript" src="https://cdn.weglot.com/weglot.min.js"></script>
<script>
    Weglot.initialize({
        api_key: 'wg_90eabc8cd0c4b5bafabb42bb6dd7d8899'
    });
</script>